"""Final PDF report (guide section 20) built with ReportLab."""
from __future__ import annotations

from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

from backend.config import settings

RISK_COLORS = {"HIGH": colors.HexColor("#B42318"), "MEDIUM": colors.HexColor("#B54708"), "LOW": colors.HexColor("#2F6B4F")}
INK = colors.HexColor("#1D2939")
MUTED = colors.HexColor("#667085")
DISCLAIMER = ("LegalLens is an academic document-analysis assistant, not a substitute for qualified legal advice. "
              "Risk levels describe potential risks identified by automated checks and should be verified by a "
              "qualified professional. Reference documents are project templates, not official legal standards. "
              "Legal knowledge summaries are educational and must be verified against the official text of the law.")


def _styles():
    ss = getSampleStyleSheet()
    base = ParagraphStyle("base", parent=ss["BodyText"], fontName="Helvetica", fontSize=9.5, leading=13.5, textColor=INK,
                          alignment=TA_LEFT)
    return {
        "title": ParagraphStyle("title", parent=base, fontName="Helvetica-Bold", fontSize=22, leading=26, spaceAfter=4),
        "subtitle": ParagraphStyle("subtitle", parent=base, fontSize=11, textColor=MUTED, spaceAfter=14),
        "h1": ParagraphStyle("h1", parent=base, fontName="Helvetica-Bold", fontSize=13.5, leading=17, spaceBefore=12, spaceAfter=6),
        "h2": ParagraphStyle("h2", parent=base, fontName="Helvetica-Bold", fontSize=10.5, leading=14, spaceBefore=8, spaceAfter=3),
        "body": base,
        "quote": ParagraphStyle("quote", parent=base, fontName="Times-Roman", fontSize=10, leading=14, leftIndent=8,
                                borderColor=colors.HexColor("#D0D5DD"), borderWidth=0, textColor=colors.HexColor("#344054")),
        "small": ParagraphStyle("small", parent=base, fontSize=8, leading=11, textColor=MUTED),
        "cell": ParagraphStyle("cell", parent=base, fontSize=8.5, leading=11),
    }


def _p(text, style):
    return Paragraph(escape(str(text or "")).replace("\n", "<br/>"), style)


def _table(rows, widths, header=True):
    t = Table(rows, colWidths=widths, repeatRows=1 if header else 0)
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D0D5DD")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EEF2F6") if header else colors.white),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(18 * mm, 10 * mm, "LegalLens — academic analysis, not legal advice")
    canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_report(document, clauses, comparisons, persona_summaries, conversations) -> str:
    st = _styles()
    out = settings.REPORTS_DIR / f"LegalLens_Report_doc{document.document_id}.pdf"
    doc = SimpleDocTemplate(str(out), pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm,
                            bottomMargin=16 * mm, title=f"LegalLens report — {document.filename}")
    W = A4[0] - 36 * mm
    story = [_p("LEGAL LENS", st["title"]), _p("Legal document analysis report", st["subtitle"])]
    meta = document.analysis_meta or {}

    story.append(_p("1. Document information", st["h1"]))
    info = [["Field", "Value"], ["File name", document.filename],
            ["Document type", f"{document.detected_type} ({'selected by user' if document.document_type != 'auto' else 'auto-detected'})"],
            ["Uploaded", document.upload_date.strftime("%d %b %Y %H:%M") if document.upload_date else ""],
            ["Analysed", document.processed_at.strftime("%d %b %Y %H:%M") if document.processed_at else ""],
            ["Pages / characters", f"{document.page_count} / {document.char_count}"],
            ["Text extraction", document.extraction_method or ""],
            ["Explanations generated by", meta.get("generation", "")],
            ["Embeddings / vector store", f"{meta.get('embedding_backend', '')} / {meta.get('vector_store', '')}"],
            ["Report generated", datetime.now().strftime("%d %b %Y %H:%M")]]
    story.append(_table([[_p(a, st["cell"]), _p(b, st["cell"])] for a, b in info], [45 * mm, W - 45 * mm]))

    story.append(_p("2. Overall summary", st["h1"]))
    story.append(_p(document.overall_summary, st["body"]))
    story.append(_p(f"Generated by: {document.summary_method}", st["small"]))

    story.append(_p("3. Clause classification", st["h1"]))
    counts = {}
    for c in clauses:
        counts.setdefault(c.clause_type, {"n": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0})
        counts[c.clause_type]["n"] += 1
        counts[c.clause_type][c.risk_level or "LOW"] += 1
    rows = [["Category", "Clauses", "High", "Medium", "Low"]] + [[k, v["n"], v["HIGH"], v["MEDIUM"], v["LOW"]] for k, v in counts.items()]
    story.append(_table([[_p(x, st["cell"]) for x in r] for r in rows], [W * 0.36] + [W * 0.16] * 4))
    story.append(Spacer(1, 6))
    # Printed numbering when the document has it (unnumbered units such as the preamble get "—"),
    # otherwise the clause's position.
    labelled = any(c.label for c in clauses)
    ref = (lambda c: c.label or "—") if labelled else (lambda c: str(c.clause_number))
    rows = [["#", "Title", "Category", "Risk"]] + [[ref(c), c.title or "—", c.clause_type, c.risk_level] for c in clauses]
    t = _table([[_p(x, st["cell"]) for x in r] for r in rows], [12 * mm, W * 0.5, W * 0.22, W - 12 * mm - W * 0.72])
    for i, c in enumerate(clauses, start=1):
        t.setStyle(TableStyle([("TEXTCOLOR", (3, i), (3, i), RISK_COLORS.get(c.risk_level, INK))]))
    story.append(t)

    story.append(PageBreak())
    story.append(_p("4. Clause-wise analysis", st["h1"]))
    for c in clauses:
        color = RISK_COLORS.get(c.risk_level, INK).hexval()[2:]
        block = [_p((f"Clause {ref(c)}: " if ref(c) != "—" else "") + (c.title or c.clause_type), st["h2"]),
                 Paragraph(f"<b>Category:</b> {escape(c.clause_type or '')} "
                           f"(confidence {c.category_confidence or 0:.2f}) &nbsp; <b>Potential risk:</b> "
                           f"<font color='#{color}'><b>{escape(c.risk_level or '')}</b></font>", st["body"]),
                 _p("Original clause:", st["small"]), _p(c.original_text, st["quote"]),
                 _p("Explanation:", st["small"]), _p(c.summary, st["body"]),
                 _p("Risk reason:", st["small"]), _p(c.risk_reason, st["body"]),
                 _p("Precaution:", st["small"]), _p(c.precaution, st["body"])]
        sources = sorted({e["source"] for e in (c.risk_evidence or []) if e.get("level") != "LOW"})
        if sources:
            block.append(_p("Evidence based on: " + "; ".join(sources), st["small"]))
        block.append(Spacer(1, 6))
        story.append(KeepTogether(block[:6]))
        story.extend(block[6:])

    story.append(_p("5. Persona-based summary", st["h1"]))
    if persona_summaries:
        for ps in persona_summaries:
            story.append(_p(ps.persona.title(), st["h2"]))
            story.append(_p(ps.summary, st["body"]))
            story.append(_p(f"Generated by: {ps.method}", st["small"]))
    else:
        story.append(_p("No persona summary was generated for this document.", st["body"]))

    story.append(_p("6. Standard document comparison", st["h1"]))
    story.append(_p("Compared against: Project reference template (not an official legal standard).", st["small"]))
    if comparisons:
        rows = [["Clause", "Reference", "User document", "Status"]]
        for r in comparisons:
            rows.append([r.category + (f" ({r.standard_title})" if r.standard_title else ""), r.standard_value,
                         r.user_value + (f" [cl. {r.user_clause_label or r.user_clause_number}]" if r.user_clause_number else ""), r.status])
        story.append(_table([[_p(x, st["cell"]) for x in row] for row in rows], [W * 0.3, W * 0.22, W * 0.3, W * 0.18]))
        story.append(Spacer(1, 4))
        for r in comparisons:
            if r.status in ("differs", "missing"):
                story.append(_p(f"• {r.category}: {r.difference}", st["body"]))
    else:
        story.append(_p("No reference template is available for this document type.", st["body"]))

    story.append(_p("7. Q&A summary", st["h1"]))
    if conversations:
        for q in conversations:
            story.append(_p(f"Q: {q.question}", st["h2"]))
            story.append(_p(q.answer, st["body"]))
    else:
        story.append(_p("No questions were asked about this document.", st["body"]))

    story.append(_p("8. Recommendations", st["h1"]))
    for rec in document.recommendations or []:
        story.append(_p(f"• [{rec['priority']}] {rec['text']}", st["body"]))
    if not document.recommendations:
        story.append(_p("No specific recommendations.", st["body"]))

    story.append(_p("9. Disclaimer", st["h1"]))
    story.append(_p(DISCLAIMER, st["body"]))
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return str(out)
