import { useState } from "react";
import RiskBadge from "./RiskBadge.jsx";

export default function ClauseDetail({ clause, comparison }) {
  const [showRefs, setShowRefs] = useState(false);
  if (!clause) return <div className="clause-detail empty">Select a clause to see its explanation and potential risk.</div>;
  const cls = clause.classifier_details || {};
  return (
    <article className="clause-detail" aria-live="polite">
      <header>
        <h3>
          <span className="clause-num">{clause.label || clause.clause_number}</span>
          {clause.title || clause.clause_type}
        </h3>
        <div className="detail-tags">
          <span className="cat-tag">{clause.clause_type}</span>
          <RiskBadge level={clause.risk_level} />
        </div>
      </header>

      <section>
        <h4>Original clause</h4>
        <blockquote className="original">{clause.original_text}</blockquote>
      </section>

      <section>
        <h4>In plain language</h4>
        <p className="explanation">{clause.summary}</p>
        <p className="method">Generated by: {clause.summary_method}</p>
      </section>

      <section className={`risk-box risk-${(clause.risk_level || "none").toLowerCase()}`}>
        <h4>Potential risk: {clause.risk_level}</h4>
        <p>{clause.risk_reason}</p>
        {clause.risk_evidence?.length > 0 && (
          <ul className="evidence">
            {clause.risk_evidence.map((e, i) => (
              <li key={i}>
                <span className={`lvl risk-${e.level.toLowerCase()}`}>{e.level}</span>
                <strong>{e.finding}</strong> — {e.reason}
                {e.source && <span className="source"> Source: {e.source}</span>}
              </li>
            ))}
          </ul>
        )}
        <h4>Precaution</h4>
        <p>{clause.precaution}</p>
        <p className="method">Assessed by: {clause.risk_method}</p>
      </section>

      {(clause.standard_match || comparison) && (
        <section>
          <h4>Reference template comparison</h4>
          {comparison && (
            <table className="mini-compare">
              <tbody>
                <tr><th>Reference</th><td>{comparison.standard_value}</td></tr>
                <tr><th>This document</th><td>{comparison.user_value}</td></tr>
              </tbody>
            </table>
          )}
          {comparison?.difference && <p>{comparison.difference}</p>}
          {clause.standard_match && (
            <>
              <blockquote className="reference">{clause.standard_match.text}</blockquote>
              <p className="method">{clause.standard_match.label} · similarity {clause.standard_match.score?.toFixed(2)}</p>
            </>
          )}
        </section>
      )}

      <section>
        <button className="linklike" onClick={() => setShowRefs(!showRefs)} aria-expanded={showRefs}>
          {showRefs ? "Hide" : "Show"} retrieved reference knowledge ({clause.references?.length || 0}) and classifier details
        </button>
        {showRefs && (
          <div className="refs">
            {clause.references?.map((r, i) => (
              <div key={i} className="ref">
                <p><strong>{r.title}</strong> <span className="muted">— {r.source} · score {r.score?.toFixed(2)}</span></p>
                {r.citation && <p className="muted small">{r.citation}</p>}
                <p className="small">{r.text}</p>
              </div>
            ))}
            <p className="small muted">
              Category: {clause.clause_type} (confidence {clause.category_confidence?.toFixed(2)}, {cls.method}).
              Keyword baseline: {cls.keyword?.label}; embedding similarity: {cls.embedding?.label}
              {cls.ml && <>; ML classifier: {cls.ml.label} ({cls.ml.confidence?.toFixed(2)})</>}.
            </p>
          </div>
        )}
      </section>
    </article>
  );
}
