import { useEffect, useState } from "react";
import { api } from "../api.js";

export default function PersonaPanel({ documentId }) {
  const [available, setAvailable] = useState([]);
  const [summaries, setSummaries] = useState({});
  const [persona, setPersona] = useState("employee");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    api.personas(documentId).then((d) => {
      setAvailable(d.available);
      setSummaries(Object.fromEntries(d.summaries.map((s) => [s.persona, s])));
    }).catch((e) => setError(e.message));
  }, [documentId]);

  const generate = async () => {
    setBusy(true);
    setError("");
    try {
      const s = await api.generatePersona(documentId, persona);
      setSummaries({ ...summaries, [persona]: s });
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  };

  const current = summaries[persona];
  return (
    <section className="persona">
      <div className="persona-controls">
        <label className="inline">
          Explain this document as
          <select value={persona} onChange={(e) => setPersona(e.target.value)}>
            {available.map((p) => <option key={p.key} value={p.key}>{p.label}</option>)}
          </select>
        </label>
        <button className="primary" onClick={generate} disabled={busy}>
          {busy ? "Generating…" : current ? "Regenerate summary" : "Generate summary"}
        </button>
      </div>
      {error && <p className="error">{error}</p>}
      {current ? (
        <article className="persona-text">
          {current.summary.split("\n").map((line, i) => line.trim() === "" ? <br key={i} /> : <p key={i}>{line}</p>)}
          <p className="method">Generated by: {current.method} · {new Date(current.created_at).toLocaleString()}</p>
        </article>
      ) : (
        <p className="muted">Choose a perspective and generate a summary. It is saved and included in the PDF report.</p>
      )}
    </section>
  );
}
